language: ruby
dist: trusty
sudo: false
cache: bundler

rvm:
  - 2.4.1

before_install:
  - gem install bundler --no-document
  - bundle install

before_script:
  - bin/rails db:migrate

script:
  - bundle exec rubocop
  - bin/rails test
